### ISSUE TITLE
The engine "node" is incompatible with this module

### ISSUE THREAD

**Issue by ishak-lm** [GoogleCloudPlatform/nodejs-docker#233]
Following this issue https://stackoverflow.com/questions/72052616/google-app-engine-the-engine-node-is-incompatible-with-this-module and this one too https://github.com/GoogleCloudPlatform/nodejs-docker/issues/214, we still have an issue with the Node version.

This questions has been asked many times already, and I checked all the answers but none of them helped me.

I'm trying to deploy a NodeJs app to GAE using a app.yml file. It was working perfectly until my last Github PR on it where I upgraded some nodes modules.

Now I'm getting the Error The engine "node" is incompatible with this module. Expected version "16.x.x". Got "12.19.0".

As you can see I'm up to date on my computer. I also removed and install Node, Npm and Yarn tonight just to be sure.

```
node -v
v16.15.0
npm -v
8.5.5
yarn -v
1.22.18
```

I tried deploying the app with a specific node version on my packages.json but with or without it's not working.

```
  "engines": {
    "node": "16.x.x"
  },
```

I also tried to remove the cache on GAE using this, without no effect.

```
default_expiration: '0d 0h'
```

On my app.yml I'm using nodejs en Env: flex:

```
runtime: nodejs
env: flex
```

I can't use node16 as I need env: flex.

Of course I tried to delete the Node_modules and yarn.lock for at least 100 times but still nothing, always the same error.

Nothing change on the app.yml file since the last deployment. The only thing is that I upgraded some Node Modules.

On the Yarn side I've tried:

```
yarn install --force
yarn install --ignore-engines
yarn cache clean --all
```

But still not working.

```

# [START app_yaml]
runtime: custom
env: flex

# default_expiration: '0d 0h'


# Define environment variable
env_variables:
  # NodeJS
  NODE_ENV: 'prod'
  APP_PORT: 8080


beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: '********'
# Resources configuration (for each server)
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
# Configuration of automatic scaling
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 3
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.6
# [END app_yaml]

```

Any help will be really grateful.
