### ISSUE TITLE
app.yaml does not propagate env variables to dockerfile for custom runtime

### ISSUE THREAD

**Issue by OleksiiKachan** [GoogleCloudPlatform/nodejs-docker#250]
facing same issue as https://github.com/GoogleCloudPlatform/nodejs-docker/issues/56

```
runtime: custom
env: flex
env_variables:
  NODE_ENV: 
  STRAPI_URL:  
  DATABASE_HOST: 
  DATABASE_PORT:
  DATABASE_NAME:
  DATABASE_USERNAME:
  DATABASE_PASSWORD:
  DATABASE_SCHEMA:
  GCS_BUCKET_NAME: 
  GCS_BASE_PATH:
```

dockerfile:
```
FROM gcr.io/google-appengine/nodejs

RUN install_node v14.20.0

COPY . .

RUN printenv

RUN yarn install --non-interactive --frozen-lockfile

RUN yarn build --clean

CMD yarn start
```

printenv output does not have any of my envs from app.yaml
```
HOSTNAME=3fd0c12a6106
PORT=8080
HOME=/root
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/nodejs/bin
DEBIAN_FRONTEND=noninteractive
PWD=/app
NODE_ENV=production
```
